## Build the application
FROM maven:3.9.5-amazoncorretto-21 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean install -DskipTests

## Run the application
FROM openjdk:21-oracle
WORKDIR /app
COPY --from=build /app/target/calendarapi-0.0.1-SNAPSHOT.jar ./events-api.jar
EXPOSE 9090

ENV DB_URI ${DB_URI}
ENV SECRET_KEY ${SECRET_KEY}

CMD [ "java", "-jar", "events-api.jar" ]